# Action Cable uses Redis by default to administer connections, channels, and sending/receiving messages over the WebSocket.
production:
  adapter: redis
  url: redis://192.168.0.104:6379/1

development:
  adapter: async

test:
  adapter: async
